# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute an exponential quadratic covariance matrix, also known as a squared exponential
#'
#' @param xa \code{NumericVector} of values
#' @param xb \code{NumericVector} of values
#' @param sigma \code{double} denoting the variance
#' @param l \code{double} denoting the lengthscale
#' @return \code{NumericMatrix} of covariance
#' @author Trent Henderson
#' @examples
#' x1 <- seq(from = -2, to = 2, length.out = 100)
#' cov_exp_quad_cpp(x1, x1, 0.05, 1)
cov_exp_quad_cpp <- function(xa, xb, sigma, l) {
    .Call('_tsgp_cov_exp_quad_cpp', PACKAGE = 'tsgp', xa, xb, sigma, l)
}

#' Compute a linear covariance matrix
#'
#' @param xa \code{NumericVector} of values
#' @param xb \code{NumericVector} of values
#' @param sigma_b \code{double} denoting the constant variance
#' @param sigma_v \code{double} denoting the variance
#' @param c \code{double} denoting the offset
#' @return \code{NumericMatrix} of covariance
#' @author Trent Henderson
#' @examples
#' x1 <- seq(from = -2, to = 2, length.out = 100)
#' cov_linear_cpp(x1, x1, 0.05, 1, 1)
cov_linear_cpp <- function(xa, xb, sigma_b, sigma_v, c) {
    .Call('_tsgp_cov_linear_cpp', PACKAGE = 'tsgp', xa, xb, sigma_b, sigma_v, c)
}

#' Compute a white noise covariance matrix
#'
#' @param xa \code{NumericVector} of values
#' @param xb \code{NumericVector} of values
#' @param sigma \code{double} denoting the variance
#' @return \code{NumericMatrix} of covariance
#' @author Trent Henderson
#' @examples
#' x1 <- seq(from = -2, to = 2, length.out = 100)
#' cov_noise_cpp(x1, x1, 0.5)
cov_noise_cpp <- function(xa, xb, sigma) {
    .Call('_tsgp_cov_noise_cpp', PACKAGE = 'tsgp', xa, xb, sigma)
}

#' Compute a periodic covariance matrix
#'
#' @param xa \code{NumericVector} of values
#' @param xb \code{NumericVector} of values
#' @param sigma \code{double} denoting the variance
#' @param l \code{double} denoting the lengthscale
#' @param p \code{int} denoting the period
#' @return \code{NumericMatrix} of covariance
#' @author Trent Henderson
#' @examples
#' x1 <- seq(from = -2, to = 2, length.out = 100)
#' cov_periodic_cpp(x1, x1, 0.05, 1, 1)
cov_periodic_cpp <- function(xa, xb, sigma, l, p) {
    .Call('_tsgp_cov_periodic_cpp', PACKAGE = 'tsgp', xa, xb, sigma, l, p)
}

#' Compute a rational quadratic covariance matrix
#'
#' @param xa \code{NumericVector} of values
#' @param xb \code{NumericVector} of values
#' @param sigma \code{double} denoting the variance
#' @param alpha \code{double} greater than \code{0} denoting the mixing coefficient
#' @param l \code{double} denoting the lengthscale
#' @return \code{NumericMatrix} of covariance
#' @author Trent Henderson
#' @examples
#' x1 <- seq(from = -2, to = 2, length.out = 100)
#' cov_rat_quad_cpp(x1, x1, 0.05, 1, 1)
cov_rat_quad_cpp <- function(xa, xb, sigma, alpha, l) {
    .Call('_tsgp_cov_rat_quad_cpp', PACKAGE = 'tsgp', xa, xb, sigma, alpha, l)
}

